// Generated by https://quicktype.io

export interface IPig {
  id_pig:        number;
  id_pig_type:   number;
  id_ubication:  number;
  id_race:       number;
  code:          string;
  added_date:    string | Date;
  created_at:    string | Date;
  id_stallion:   number;
  visible:       boolean;
  id_farm:       number;
  id_stage_type:      number;
  status:        boolean;
  pig_type:      string;
  pig_ubication: string;
  pig_race:      string;
  pig_stage:     string;
  stallion?:     string;
  id_weight_type:number;
  pig_weight?:string;
}

export interface IStallion {
  id_stallion:  number;
  name:         string;
  status:       boolean;
  id_ubication: number;
  id_race:      number;
  created_at:   string | Date;
  id_farm:      number;
}

export interface IBirth {
  id_birth:        number;
  id_pig:          number;
  id_stallion:     number;
  birth_date:      string;
  confirm_date:    string;
  crossing_date:   string;
  is_positive:     boolean;
  alive:           number;
  dead:            number;
  description:     string;
  status:          boolean;
  created_at:      string;
  id_user:         number;
  id_user_confirm: number;
  id_user_birth:   number;
  id_fertilization_type:number;
  fertilization_type?:string;
  stallion?:string
}

export interface ICrossing{
  pig:IPig;
  birth:IBirth
}


export interface IPigWeight {
  id_weight_type: number;
  description:    string;
  status:         boolean;
}
