// Generated by https://quicktype.io

export interface IPig {
  id_pig:        number;
  id_pig_type:   number;
  id_ubication:  number;
  id_race:       number;
  code:          string;
  start_date:    string | Date;
  visible:       boolean;
  id_farm:       number;
  id_stage:      number;
  status:        boolean;
  pig_type:      string;
  pig_ubication: string;
  pig_race:      string;
  pig_stage:     string;
}

export interface IStallion {
  id_stallion:  number;
  name:         string;
  status:       boolean;
  id_ubication: number;
  id_race:      number;
  created_at:   string | Date;
  id_farm:      number;
}
