// Generated by https://quicktype.io

export interface IPig {
  id_pig:        number;
  id_pig_type:   number;
  id_ubication:  number;
  id_race:       number;
  code:          string;
  added_date:    string | Date;
  created_at:    string | Date;
  id_stallion:   number;
  visible:       boolean;
  id_farm:       number;
  id_pig_stage:      number;
  status:        boolean;
  pig_type:      string;
  pig_ubication: string;
  pig_race:      string;
  pig_stage:     string;
  bar_code:     string;
  stallion?:     string;
  id_weight_type:number;
  pig_weight?:string;
  is_active:boolean;
  next_birth:string | Date | null;
  month_name:string | null
  counting_days: string | null;
  births:number;
  piglets:number;
  gate_piglets:number;
  crossing_stallion:string|null;
  crossing_date:string;
  false_charge:number;
  abortions:number;
}

export interface IStallion {
  id_stallion:  number;
  name:         string;
  status:       boolean;
  id_ubication: number;
  id_race:      number;
  created_at:   string | Date;
  id_farm:      number;
  total_alive:number;
  total_dead:number;
  false_charge:number;
  total_effective:number;
}

export interface IBirth {
  id_birth:        number;
  id_pig:          number;
  id_stallion:     number;
  birth_date:      string | Date;
  confirm_date:    string | Date;
  crossing_date:   string | Date;
  is_positive:     boolean;
  alive:           number | string;
  dead:            number | string;
  description:     string;
  status:          boolean;
  created_at:      string | Date;
  id_user:         number;
  id_user_confirm: number;
  id_user_birth:   number;
  id_birth_type:number;
  birth_type?: string;
  id_fertilization_type:number;
  fertilization_type?:string;
  stallion?:string;
  comment:string;
  closed:boolean;
}

export interface ICrossing{
  pig:IPig;
  birth:IBirth
}


export interface IPigWeight {
  id_weight_type: number;
  description:    string;
  status:         boolean;
}
